version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:80"  # 监听端口映射
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_SILICONFLOW_API_URL=${SILICONFLOW_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:8000"  # 开发端口映射
    environment:
      - MONGODB_URL=mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/ai_novel_db?authSource=admin
      - DATABASE_SYSTEM_URL=mysql+aiomysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_SYSTEMHOST}:3306/${DATABASE_SYSTEM}
      - DATABASE_NOVEL_URL=mysql+aiomysql://${DATABASE_NOVELUSER}:${DATABASE_NOVELUSER_PASSWORD}@${DATABASE_NOVELHOST}:3306/${DATABASE_NOVELDATA}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_DEFAULT_MODEL=${SILICONFLOW_DEFAULT_MODEL}
      - SILICONFLOW_API_URL=${SILICONFLOW_API_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost:80,http://127.0.0.1:80,http://localhost:8080,http://127.0.0.1:8080,http://${SERVER_IP}:80,http://${SERVER_IP}:8080
      - MCP_SERVER_NAME=${MCP_SERVER_NAME}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT}
      - MCP_SERVER_HOST=${MCP_SERVER_HOST}
      - MCP_TOOLS_ENABLED=${MCP_TOOLS_ENABLED}
      - MCP_TOOLS_LIST=${MCP_TOOLS_LIST}
      - NOVEL_GENERATION_MAX_TOKENS=${NOVEL_GENERATION_MAX_TOKENS}
      - NOVEL_GENERATION_TEMPERATURE=${NOVEL_GENERATION_TEMPERATURE}
      - NOVEL_GENERATION_TOP_P=${NOVEL_GENERATION_TOP_P}
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  # MongoDB数据库
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=ai_novel_db
    volumes:
      - mongodb_data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    restart: unless-stopped

  # Redis缓存 (用于会话管理)
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: >
      sh -c "
        if [ -n \"${REDIS_PASSWORD}\" ]; then
          redis-server --requirepass \"${REDIS_PASSWORD}\"
        else
          redis-server
        fi
      "
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
