version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:80"  # 监听端口映射
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_SILICONFLOW_API_URL=${SILICONFLOW_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:8000"  # 开发端口映射
    environment:
      - MONGODB_URL=mongodb://${MONGODB_HOST:-172.16.16.2}:${MONGODB_PORT:-27017}/${MONGODB_DATABASE:-ai_novel_db}
      - DATABASE_SYSTEM_URL=mysql+aiomysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_SYSTEMHOST}:3306/${DATABASE_SYSTEM}
      - DATABASE_NOVEL_URL=mysql+aiomysql://${DATABASE_NOVELUSER}:${DATABASE_NOVELUSER_PASSWORD}@${DATABASE_NOVELHOST}:3306/${DATABASE_NOVELDATA}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST:-172.16.16.4}:${REDIS_PORT:-6379}
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_DEFAULT_MODEL=${SILICONFLOW_DEFAULT_MODEL}
      - SILICONFLOW_API_URL=${SILICONFLOW_API_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost:80,http://127.0.0.1:80,http://localhost:8080,http://127.0.0.1:8080,http://${SERVER_IP}:80,http://${SERVER_IP}:8080
      - MCP_SERVER_NAME=${MCP_SERVER_NAME}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT}
      - MCP_SERVER_HOST=${MCP_SERVER_HOST}
      - MCP_TOOLS_ENABLED=${MCP_TOOLS_ENABLED}
      - MCP_TOOLS_LIST=${MCP_TOOLS_LIST}
      - NOVEL_GENERATION_MAX_TOKENS=${NOVEL_GENERATION_MAX_TOKENS}
      - NOVEL_GENERATION_TEMPERATURE=${NOVEL_GENERATION_TEMPERATURE}
      - NOVEL_GENERATION_TOP_P=${NOVEL_GENERATION_TOP_P}
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

networks:
  app-network:
    driver: bridge
