services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_SILICONFLOW_API_URL=${SILICONFLOW_API_URL:-https://api.siliconflow.cn/v1}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # 后端服务 - 生产环境使用云数据库
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # 生产环境使用云数据库服务 - 使用实际配置
      - MONGODB_URL=mongodb://${MONGODB_HOST:-mongodb-server}:${MONGODB_PORT:-27017}/${MONGODB_DATABASE:-ai_novel_db}
      - DATABASE_SYSTEM_URL=mysql+aiomysql://${DATABASE_USER:-lkr}:${DATABASE_PASSWORD:-Lekairong350702}@${DATABASE_SYSTEMHOST:-172.16.16.3}:${DATABASE_PORT:-3306}/${DATABASE_SYSTEM:-novel_data}
      - DATABASE_NOVEL_URL=mysql+aiomysql://${DATABASE_NOVELUSER:-novel_data_user}:${DATABASE_NOVELUSER_PASSWORD:-Lekairong350702}@${DATABASE_NOVELHOST:-172.16.16.2}:${DATABASE_PORT:-3306}/${DATABASE_NOVELDATA:-novel_user_data}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-Lekairong350702}@${REDIS_HOST:-redis-server}:${REDIS_PORT:-6379}
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY:-sk-mjithqmjwccqgffouexthbavtnvftwkqjludpcxhrmeztcib}
      - SILICONFLOW_DEFAULT_MODEL=${SILICONFLOW_DEFAULT_MODEL:-deepseek-ai/DeepSeek-V3}
      - SILICONFLOW_API_URL=${SILICONFLOW_API_URL:-https://api.siliconflow.cn/v1/chat/completions}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-this}
      - CORS_ORIGINS=http://localhost:80,http://127.0.0.1:80,http://localhost:8080,http://127.0.0.1:8080,http://${SERVER_IP:-106.13.216.179}:80,http://${SERVER_IP:-106.13.216.179}:8080
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-novel-ai-server}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-8000}
      - MCP_SERVER_HOST=${MCP_SERVER_HOST:-106.13.216.179}
      - MCP_TOOLS_ENABLED=${MCP_TOOLS_ENABLED:-true}
      - MCP_TOOLS_LIST=${MCP_TOOLS_LIST:-novel_generation,character_creation,plot_analysis,content_review,style_transfer}
      - NOVEL_GENERATION_MAX_TOKENS=${NOVEL_GENERATION_MAX_TOKENS:-4096}
      - NOVEL_GENERATION_TEMPERATURE=${NOVEL_GENERATION_TEMPERATURE:-0.8}
      - NOVEL_GENERATION_TOP_P=${NOVEL_GENERATION_TOP_P:-0.9}
    networks:
      - app-network
    extra_hosts:
      - "mongodb-server:172.16.32.2"
      - "redis-server:172.16.32.2"
      - "mysql-system:172.16.16.3"
      - "mysql-user:172.16.16.2"
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

networks:
  app-network:
    driver: bridge
