#!/bin/bash

# 🤖 GitHub Actions 错误分析和修复 - 简化使用脚本
# 一键分析最新的部署错误并自动生成修复方案

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
cat << 'EOF'
   ______ _ _   _   _       _         _____      _   _                 
  / ___(_) | | | | | |_   _| |__     /  ___|    | | (_)                
 / /   _| | |_| |_| | | | | '_ \    \ `--.  ___| |_ _  ___  _ __  ___  
| |   | | __| __| | | | | | |_) |    `--. \/ _ \ __| |/ _ \| '_ \/ __| 
| |___| | |_| |_| | |_| | |_) |     /\__/ /  __/ |_| | (_) | | | \__ \ 
 \____|_|\__|\__|_|\__,_|_.__/      \____/ \___|\__|_|\___/|_| |_|___/ 
                                                                       
    🤖 AI小说编辑器 - 智能部署错误分析系统
EOF
echo -e "${NC}"

echo "=================================================="
echo -e "${YELLOW}🚀 开始自动分析GitHub Actions部署错误...${NC}"
echo ""

# 检查必要工具
check_tools() {
    echo -e "${YELLOW}📋 检查必要工具...${NC}"
    
    local missing_tools=()
    
    if ! command -v python3 &> /dev/null; then
        missing_tools+=("python3")
    fi
    
    if ! command -v pip3 &> /dev/null; then
        missing_tools+=("pip3")
    fi
    
    if [ ${#missing_tools[@]} -ne 0 ]; then
        echo -e "${RED}❌ 缺少必要工具: ${missing_tools[*]}${NC}"
        echo -e "${YELLOW}💡 安装命令:${NC}"
        echo "   sudo apt update"
        echo "   sudo apt install python3 python3-pip"
        exit 1
    fi
    
    echo -e "${GREEN}✅ 工具检查完成${NC}"
}

# 安装Python依赖
install_dependencies() {
    echo -e "${YELLOW}📦 安装Python依赖...${NC}"
    
    pip3 install --quiet requests >/dev/null 2>&1 || {
        echo -e "${RED}❌ 依赖安装失败${NC}"
        echo -e "${YELLOW}💡 请手动安装: pip3 install requests${NC}"
        exit 1
    }
    
    echo -e "${GREEN}✅ 依赖安装完成${NC}"
}

# 检查GitHub Token
check_github_token() {
    echo -e "${YELLOW}🔐 检查GitHub访问权限...${NC}"
    
    if [ -z "$GITHUB_TOKEN" ]; then
        echo -e "${RED}❌ 未设置GITHUB_TOKEN环境变量${NC}"
        echo ""
        echo -e "${YELLOW}💡 获取GitHub Token:${NC}"
        echo "1. 访问: https://github.com/settings/tokens"
        echo "2. 创建新的Personal Access Token"
        echo "3. 选择 'repo' 和 'actions:read' 权限"
        echo "4. 复制生成的token"
        echo ""
        echo -e "${YELLOW}💡 设置环境变量:${NC}"
        echo "export GITHUB_TOKEN=your_token_here"
        echo ""
        read -p "请输入您的GitHub Token: " token
        
        if [ -z "$token" ]; then
            echo -e "${RED}❌ Token不能为空${NC}"
            exit 1
        fi
        
        export GITHUB_TOKEN="$token"
    fi
    
    echo -e "${GREEN}✅ GitHub Token已配置${NC}"
}

# 运行智能分析
run_analysis() {
    echo -e "${YELLOW}🤖 运行智能错误分析...${NC}"
    
    # 设置仓库信息
    export GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER:-"your-username"}
    export GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-"legezhixiao"}
    
    # 运行Python分析脚本
    python3 github-actions-analyzer.py
}

# 应用自动修复
apply_fixes() {
    echo -e "${YELLOW}🔧 检查是否有可应用的修复...${NC}"
    
    if ls fix-*.sh 1> /dev/null 2>&1; then
        echo -e "${GREEN}🛠️ 发现修复脚本！${NC}"
        echo ""
        
        for script in fix-*.sh; do
            echo -e "${BLUE}🔧 运行修复脚本: $script${NC}"
            chmod +x "$script"
            
            if ./"$script"; then
                echo -e "${GREEN}   ✅ $script 执行成功${NC}"
            else
                echo -e "${RED}   ❌ $script 执行失败${NC}"
            fi
            echo ""
        done
        
        echo -e "${GREEN}🎉 所有修复脚本执行完成！${NC}"
        
        # 询问是否提交修复
        echo ""
        read -p "是否要提交这些修复？(y/N): " -n 1 -r
        echo
        
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            commit_fixes
        else
            echo -e "${YELLOW}ℹ️ 修复未提交，您可以手动检查后再提交${NC}"
        fi
        
    else
        echo -e "${GREEN}ℹ️ 未发现需要应用的修复脚本${NC}"
        echo -e "${YELLOW}💡 这意味着没有检测到可自动修复的问题${NC}"
    fi
}

# 提交修复
commit_fixes() {
    echo -e "${YELLOW}📤 提交修复到Git仓库...${NC}"
    
    # 配置Git用户信息
    git config --local user.email "auto-fix@github.com"
    git config --local user.name "GitHub Actions Auto-Fix"
    
    # 添加所有修改的文件
    git add .
    
    # 检查是否有变更
    if git diff --staged --quiet; then
        echo -e "${YELLOW}ℹ️ 没有需要提交的变更${NC}"
    else
        # 创建提交
        commit_message="🔧 自动修复部署问题

- 通过智能错误分析系统检测并修复问题
- 应用自动生成的修复方案
- 详细信息请查看 deployment-analysis-report.md

Auto-generated by GitHub Actions Error Analyzer"
        
        git commit -m "$commit_message"
        
        echo -e "${GREEN}✅ 修复已提交到本地仓库${NC}"
        
        # 询问是否推送
        read -p "是否要推送到远程仓库？(y/N): " -n 1 -r
        echo
        
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git push
            echo -e "${GREEN}🚀 修复已推送！新的部署将自动开始${NC}"
        else
            echo -e "${YELLOW}ℹ️ 修复已提交但未推送，请手动推送: git push${NC}"
        fi
    fi
}

# 显示分析结果
show_results() {
    echo ""
    echo -e "${BLUE}📊 分析结果总结${NC}"
    echo "=================================================="
    
    if [ -f "deployment-analysis-report.md" ]; then
        echo -e "${GREEN}✅ 详细分析报告: deployment-analysis-report.md${NC}"
    fi
    
    if ls fix-*.sh 1> /dev/null 2>&1; then
        echo -e "${GREEN}✅ 自动修复脚本:${NC}"
        for script in fix-*.sh; do
            echo "   - $script"
        done
    fi
    
    echo ""
    echo -e "${YELLOW}💡 建议后续操作:${NC}"
    echo "1. 查看详细分析报告了解问题详情"
    echo "2. 如果有修复脚本，可以重新运行此脚本应用修复"
    echo "3. 检查GitHub Secrets配置是否正确"
    echo "4. 验证服务器状态和网络连接"
    echo ""
}

# 主函数
main() {
    echo -e "${BLUE}🎯 开始智能部署错误分析流程...${NC}"
    echo ""
    
    # 检查工具
    check_tools
    
    # 安装依赖
    install_dependencies
    
    # 检查GitHub Token
    check_github_token
    
    # 运行分析
    run_analysis
    
    # 应用修复
    apply_fixes
    
    # 显示结果
    show_results
    
    echo ""
    echo -e "${GREEN}🎉 智能错误分析完成！${NC}"
    echo -e "${BLUE}🔗 更多信息请查看生成的报告和脚本${NC}"
}

# 帮助信息
show_help() {
    echo "GitHub Actions 智能错误分析和修复工具"
    echo ""
    echo "用法:"
    echo "  $0 [选项]"
    echo ""
    echo "选项:"
    echo "  -h, --help     显示此帮助信息"
    echo "  -t, --token    指定GitHub Token"
    echo ""
    echo "环境变量:"
    echo "  GITHUB_TOKEN              GitHub访问Token"
    echo "  GITHUB_REPOSITORY_OWNER   GitHub用户名"
    echo "  GITHUB_REPOSITORY         仓库名称"
    echo ""
    echo "示例:"
    echo "  # 使用环境变量中的token"
    echo "  export GITHUB_TOKEN=your_token"
    echo "  $0"
    echo ""
    echo "  # 直接指定token"
    echo "  $0 --token your_token"
}

# 参数处理
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -t|--token)
            GITHUB_TOKEN="$2"
            shift 2
            ;;
        *)
            echo -e "${RED}❌ 未知参数: $1${NC}"
            echo "使用 $0 --help 查看帮助信息"
            exit 1
            ;;
    esac
done

# 运行主函数
main
